### ISSUE TITLE
Still borked...

### ISSUE THREAD

**Issue by doobes** [binarydev/ha-generac#67] opened 2024-04-16 15:57 UTC
So,

I removed the existing integration.

Reinstalled the new version via HACS per the instructions.

![image](https://github.com/binarydev/ha-generac/assets/23409761/b96cb235-b080-4ce4-a259-a129135dada2)

Sorry...

**Comment by doobes** [comment] 2024-04-16 16:02
Never mind.... 

Dain bramage

**Comment by binarydev** [comment] 2024-04-19 21:56
This is a dupe of the other issue, so I'll close this one. I haven't released a new version yet that would allow you to debug the problem you're having more easily.

**Closed** 2024-04-19 21:56 UTC
